export type Product = {
  id: string;
  stock: number;
  sales: number;
  price: number;
  category: string;
  images: string[];
  updatedAt: string;
  storeName: string;
  colors: string[];
  createdAt: string;
  storeId: string;
  sku?:string;
  features:string[];
  rating?:number ;
  reviews?:string[];
  detailPage: string;
  productName: string;
  introducing?:string;
  description: string;
  sizes: string[];
  star?:number;
};
